sysLogo: admin_element

spring:
  profiles:
    active: dev
  freemarker:
    cache: false
    suffix: .html
    charset: utf-8
    content-type: text/html

server:
  port: 9988
  servlet:
    context-path: /api
    session:
      tracking-modes: cookie
      persistent: false  # 在重新启动之间持续会话数据。
      cookie:
        http-only: true
        max-age: 86400 # 会话cookie的最大年龄（以秒为单位）。

  tomcat:
    uri-encoding: UTF-8
    # 对于 Tomcat 头文件不限制大小
    max-swallow-size: -1
  #  servlet:
  #    context-path: /zblog
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
